# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "NGIS-OpenAPI"
  tags:
  - "public"
spec:
  type: "documentation"
  lifecycle: "production"
  owner: "ngis"
  system: "ngis"
