# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Check out head branch
        uses: actions/checkout@v2
        with:
          path: head
      - name: Check out master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: base
      - name: OpenAPI Diff
        uses: mvegter/openapi-diff-action@v0.3.0
        with:
          # Path to the BASE Swagger or OpenApi specification file.
          base-spec: base/spec/openapi.yaml
          # Path to the HEAD Swagger or OpenApi specification file.
          head-spec: head/spec/openapi.yaml
